spring:
  data:
    mongodb:
      uri: mongodb://admin:pass1234@mongodb-01:27017,mongodb-02:27018,mongodb-03:27019
      database: kohan-chat

kohan:
  authentication:
    token:
      length: 32
      expiration: 86400000
    password:
      hash:
        saltLength: 16
        hashLength: 32
        parallelism: 1
        iterations: 4
        memory: 9216
    client:
      file:
        grpc:
          host: localhost
          port: 6565
          responseTimeout: 10000

logging:
  level:
    org.mongodb.driver.cluster: "WARN"
