kohan:
  authentication:
    token:
      length: 32
      expiration: 86400000
    password:
      hash:
        saltLength: 16
        hashLength: 32
        parallelism: 1
        iterations: 4
        memory: 9216
    client:
      file:
        grpc:
          host: localhost
          port: 6565
          responseTimeout: 10000
