spring:
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    include:
      - mongo
    active: prod

kohan:
  file:
    savePath: ${FILE_SAVE_PATH}
    profileExtensions: jpg
    maxUploadFileSize: 2147483648
