spring:
  data:
    mongodb:
      uri: mongodb://chat:chatpass1234@mongodb-01:27017,mongodb-02:27018,mongodb-03:27019/kohan-chat?replicaSet=kohan-chatlogging
  level:
    org.mongodb.driver.cluster: "WARN"