name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
  merge_group:

jobs:
  build:
    name: Build, Test, and Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: latest
        mongodb-db: 'testdb'
        mongodb-username: root
        mongodb-password: root1234

    - name: Create application-test.yml in all modules
      run: |
        modules=("authentication" "file" "message-rest" "push") # 하위 모듈의 이름들
        for module in "${modules[@]}"
        do
          mkdir -p $module/src/main/resources
          echo "spring:" > $module/src/main/resources/application.yml
          echo "  data:" >> $module/src/main/resources/application.yml
          echo "    mongodb:" >> $module/src/main/resources/application.yml
          echo "      uri: mongodb://root:root1234@localhost:27017/testdb?authSource=admin" >> $module/src/main/resources/application-test.yml
        done

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
